// 3 WAYS OF TRAVERSAL

//(1) PREORDER TRAVERSAL   --> ROOT -> LEFT SUB TREE -> RIGHT SUB TREE
//(2) POSTORDER TRAVERSAL  --> LEFT SUB TREE -> RIGHT SUB TREE -> ROOT
//(3) IN ORDER TRAVERSAL   --> LEFT SUB TREE -> ROOT -> RIGHT SUB TREE